### ISSUE TITLE
"undefined reading strength" when you have a container actor

### ISSUE THREAD

**Issue by scooper4711** [HeroicLands/HarnMaster-3-FoundryVTT#322]
I upgraded to the latest version of the code and am getting the following error in the console. I haven't tested if it's having a negative impact. I need to figure out which actors are impacted. This is output multiple times.
```
TypeError: Failed initial data preparation for Actor [Lqq6hnvfcE3vHbij]: Cannot read properties of undefined (reading 'strength')
    at HarnMasterActor.prepareDerivedData (actor.js:315)
    at HarnMasterActor.prepareData (foundry.js:9414)
    at HarnMasterActor._initialize (foundry.js:9226)
    at new Document (document.mjs:51)
    at new BaseActor (documents.mjs:61)
    at new <anonymous> (foundry.js:9199)
    at new Actor (foundry.js:12113)
    at new HarnMasterActor (actor.js:10)
    at Map._initialize (foundry.js:10161)
    at new WorldCollection (foundry.js:10147)
    at new Actors (foundry.js:10351)
    at Game.initializeEntities (foundry.js:4421)
    at Game.setupGame (foundry.js:4379)
    at async Game._initializeGameView (foundry.js:5213)
```

**Comment by scooper4711** [comment]
Still an issue in v9 and system 1.3.0.

Posting stack track from v9.

```
TypeError: Cannot read properties of undefined (reading 'strength')
[Detected 1 package: system:hm3]
    at HarnMasterActor.prepareDerivedData (actor.js:315:24)
    at HarnMasterActor.prepareData (foundry.js:10729:10)
    at HarnMasterActor._initialize (foundry.js:10526:12)
    at new Document (document.mjs:52:10)
    at new BaseActor (documents.mjs:62:1)
    at new <anonymous> (foundry.js:10499:5)
    at new Actor (foundry.js:13348:5)
    at new HarnMasterActor (actor.js:10:8)
    at Actors._initialize (foundry.js:11409:15)
    at new WorldCollection (foundry.js:11395:10)
    at new Actors (foundry.js:11598:1)
    at Game.initializeDocuments (foundry.js:5584:30)
    at Game.setupGame (foundry.js:5532:10)
    at async Game._initializeGameView (foundry.js:6498:5)
```

**Comment by scooper4711** [comment]
I found it. It appears if you have a container actor.
